# Generated by Django 2.1 on 2018-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=2, verbose_name="User's role"),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit'),
        ),
    ]
