# Generated by Django 2.1 on 2018-10-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Document's Name")),
                ('description', models.TextField(null=True, verbose_name="Document's Description")),
                ('type', models.CharField(max_length=10, verbose_name="Document's Type")),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['id'],
            },
        ),
    ]
