# Generated by Django 2.1 on 2018-10-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.FileField(null=True, upload_to='', verbose_name='Content'),
        ),
    ]
