# Generated by Django 2.1 on 2018-10-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name="Course's Title")),
                ('course_code', models.CharField(max_length=20, verbose_name="Course's Code")),
                ('avatar', models.ImageField(upload_to='', verbose_name="Course's Avatar")),
                ('description', models.TextField(null=True, verbose_name="Course's Description")),
                ('course_type', models.CharField(max_length=10, verbose_name="Course's Type")),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
    ]
