# Generated by Django 2.1 on 2018-10-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181025_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstudent',
            old_name='Student_id',
            new_name='student_id',
        ),
    ]
