# Generated by Django 2.1 on 2018-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name="Class's Code"),
        ),
    ]
