# Generated by Django 2.1 on 2018-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20181031_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='', max_length=25, verbose_name="Class's Code"),
        ),
    ]
