# Generated by Django 2.1 on 2018-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name="Faculty's Code"),
        ),
    ]
