# Generated by Django 2.1 on 2018-11-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0003_auto_20181031_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustemplate',
            name='lecturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lecturer'),
        ),
        migrations.AlterField(
            model_name='syllabustemplate',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Class', verbose_name='Class'),
        ),
    ]
