# Generated by Django 2.1 on 2018-11-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_auto_20181106_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses_set', to='course.Class', verbose_name='Class'),
        ),
    ]
