# Generated by Django 2.1 on 2018-11-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_auto_20181108_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='syllabus_id',
            new_name='syllabus',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='class_id',
            new_name='own_class',
        ),
        migrations.RenameField(
            model_name='syllabustemplate',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='syllabustemplate',
            old_name='class_id',
            new_name='own_class',
        ),
    ]
