# Generated by Django 2.1 on 2018-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_auto_20181108_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOC/DOCX', 'DOC/DOCX'), ('IMG/PNG/SVG/GIF', 'IMG/PNG/SVG/GIF'), ('MP4/AVI', 'MP4/AVI'), ('MP3', 'MP3'), ('Other', 'Other')], max_length=255, verbose_name="Material's Type"),
        ),
    ]
