# Generated by Django 2.1 on 2018-12-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_auto_20181211_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabustemplate',
            name='lecturer',
        ),
    ]
