# Generated by Django 2.1 on 2018-10-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Material's Name")),
                ('material_type', models.CharField(max_length=255, verbose_name="Material's Type")),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'material',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Syllabus')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabus',
                'db_table': 'syllabus',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='syllabus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.Syllabus', verbose_name='Syllabus'),
        ),
    ]
