
import {
    AllClass,
    AsideLecturer,
    AsideStudent,
    ClassBoxLandscape,
    ClassBoxPortrait,
    InnerClass,
    MyClass,
    NewClass,
    Search
} from './class'
import ContactPage from './contact/Page.vue'
import Page from './help/Page.vue'
import LoginPage from './login/LoginContainer.vue'
import {
    Aside,
    AsideToggler,
    Breadcrumb,
    Callout,
    Footer,
    GoTopBtn,
    Header,
    HeaderDropdown,
    Sidebar,
    SidebarFooter,
    SidebarForm,
    SidebarHeader,
    SidebarMinimizer,
    SidebarNav,
    SidebarNavDivider,
    SidebarNavDropdown,
    SidebarNavItem,
    SidebarNavLabel,
    SidebarNavLink,
    SidebarNavTitle,
    SidebarToggler,
    Switch
} from './shared'

export {
    AsideStudent,
    AllClass,
    InnerClass,
    MyClass,
    NewClass,
    AsideLecturer,
    ClassBoxLandscape,
    ClassBoxPortrait,
    Search,
    ContactPage,
    Page,
    LoginPage,
    Aside,
    AsideToggler,
    Breadcrumb,
    GoTopBtn,
    Footer,
    Callout,
    Header,
    HeaderDropdown,
    Sidebar,
    SidebarFooter,
    SidebarForm,
    SidebarHeader,
    SidebarMinimizer,
    SidebarNav,
    SidebarNavDivider,
    SidebarNavDropdown,
    SidebarNavItem,
    SidebarNavLabel,
    SidebarNavLink,
    SidebarNavTitle,
    SidebarToggler,
    Switch,
}
