# Generated by Django 2.1 on 2018-11-08 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_auto_20181106_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlecturer',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classlecturer',
            name='lecturer_id',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='enrollrequest',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='enrollrequest',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='class_id',
        ),
        migrations.AddField(
            model_name='classlecturer',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_classes_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='classlecturer',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturers_set', to='course.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_set', to='course.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_set', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='enrollrequest',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wait_students_set', to='course.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='enrollrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wait_classes_set', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_set', to='course.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_set', to='course.CourseCategory', verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_set', to='course.Subject', verbose_name='Subject'),
        ),
    ]
