# Generated by Django 2.1 on 2018-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20181111_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='encoded_session',
        ),
        migrations.AddField(
            model_name='schedule',
            name='session_end',
            field=models.CharField(max_length=2, null=True, verbose_name='Session End'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='session_start',
            field=models.CharField(max_length=2, null=True, verbose_name='Session Start'),
        ),
    ]
