# Generated by Django 2.1 on 2018-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20181116_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['id'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
