# Generated by Django 2.1 on 2018-11-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20181116_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='session_end',
            field=models.CharField(max_length=2, null=True, verbose_name='Start Session'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='session_start',
            field=models.CharField(max_length=2, null=True, verbose_name='Start Session'),
        ),
    ]
