# Generated by Django 2.1 on 2018-11-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20181116_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_set', to='course.Class', verbose_name='Own Class'),
        ),
    ]
