# Generated by Django 2.1 on 2018-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20181118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time_end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='class',
            name='time_start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
