# Generated by Django 2.1 on 2018-11-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20181118_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=25, null=True, verbose_name='Code'),
        ),
    ]
