# Generated by Django 2.1 on 2018-11-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_auto_20181118_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_set', to='course.Class', verbose_name='Class'),
        ),
    ]
