# Generated by Django 2.1 on 2018-11-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_auto_20181118_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlecturer',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_classes_set', to=settings.AUTH_USER_MODEL, verbose_name='Lecturer'),
        ),
    ]
