# Generated by Django 2.1 on 2018-11-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_auto_20181118_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wait_classes_set', to=settings.AUTH_USER_MODEL, verbose_name='Request Student'),
        ),
    ]
