# Generated by Django 2.1 on 2018-10-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20181025_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsyllabus',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classsyllabus',
            name='syllabus_id',
        ),
        migrations.DeleteModel(
            name='ClassSyllabus',
        ),
    ]
