# Generated by Django 2.1 on 2018-11-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_auto_20181108_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='own_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses_set', to='course.Class', verbose_name='Class'),
        ),
    ]
