# Generated by Django 2.1 on 2018-10-25 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Class - Student',
                'verbose_name_plural': 'Classes - Students',
                'db_table': 'class_student',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Enroll Request',
                'verbose_name_plural': 'Enroll Requests',
                'db_table': 'enroll_request',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=5, verbose_name='Day Of Week')),
                ('encoded_session', models.CharField(max_length=20, verbose_name='Encoded Session')),
            ],
            options={
                'verbose_name': 'Schedule',
                'db_table': 'schedule',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='ClassUser',
            new_name='ClassLecturer',
        ),
        migrations.RemoveField(
            model_name='classsyllabus',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classsyllabus',
            name='syllabus_id',
        ),
        migrations.AlterModelOptions(
            name='classlecturer',
            options={'ordering': ['id'], 'verbose_name': 'Class - Lecturer', 'verbose_name_plural': 'Classes - Lecturers'},
        ),
        migrations.RenameField(
            model_name='classlecturer',
            old_name='user_id',
            new_name='lecturer_id',
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterModelTable(
            name='classlecturer',
            table='class_lecturer',
        ),
        migrations.DeleteModel(
            name='ClassSyllabus',
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='enrollrequest',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='enrollrequest',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Class', verbose_name='Class'),
        ),
    ]
