# Generated by Django 2.1 on 2018-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181026_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name="Class's Code"),
        ),
    ]
