# Generated by Django 2.1 on 2018-11-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20181108_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='category',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_set', to='course.CourseCategory', verbose_name='Course Category'),
        ),
    ]
